# Generated by Django 4.2.30 on 2026-07-05 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aof_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehour',
            name='request_verifier',
            field=models.ForeignKey(blank=True, help_text='Faculty member the student asked to verify these hours.', limit_choices_to={'role__in': ('faculty', 'admin')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
