# Generated by Django 4.2.30 on 2026-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aof_service', '0002_servicehour_request_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_approve_service_hours',
            field=models.BooleanField(default=True),
        ),
    ]
