# Generated by Django 5.0.6 on 2026-08-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aof_service", "0002_servicehour_request_verifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicehour",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicehour",
            name="declined_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("faculty", "admin")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="declined_verification_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
